/**
 * APM - AI Prompt Manager (Constitutional Agent)
 * 
 * Specialties: Prayer, empathy, encouragement, spiritual, biblical
 * Mission: Serve the last, the lost, and the least with compassion
 */

const { ConstitutionalAgent } = require('./constitutional-agent-base');
const express = require('express');

const PORT = process.env.PORT || 10000;

// Create APM agent
const apm = new ConstitutionalAgent({
  name: 'APM',
  specialties: ['prayer', 'empathy', 'encouragement', 'spiritual', 'biblical']
});

/**
 * APM's specialty: Process empathy and prayer tasks
 */
async function processTask(task) {
  const description = (task.description || '').toLowerCase();
  
  try {
    // Learn from how other agents handled similar tasks
    const peerWork = await apm.learnFromPeers(task.task_type);
    
    let output = '';
    let certainty = 0.85;
    
    if (description.includes('prayer') || description.includes('pray')) {
      output = await generatePrayer(task);
      certainty = 0.90;
    } else if (description.includes('encourage') || description.includes('support')) {
      output = await generateEncouragement(task);
      certainty = 0.88;
    } else if (description.includes('biblical') || description.includes('scripture')) {
      output = await findScripture(task);
      certainty = 0.85;
    } else {
      // General empathy response
      output = await generateEmpathyResponse(task);
      certainty = 0.80;
    }
    
    // Share learning if we discovered something useful
    if (certainty > 0.85 && output.length > 100) {
      await apm.shareLearning(
        `Empathy pattern for: ${task.task_type}`,
        `Approach: ${output.substring(0, 200)}...`,
        task.task_type
      );
    }
    
    return { output, certainty };
    
  } catch (err) {
    console.error('[APM] Task processing error:', err.message);
    return null;
  }
}

/**
 * Generate a prayer based on the task
 */
async function generatePrayer(task) {
  // TODO: Call free-tier LLM (Groq, DeepSeek)
  // For now, return structured response
  return `
Prayer for: ${task.title || 'This Request'}

Heavenly Father,
We come before you with humble hearts regarding: ${task.description}

Grant wisdom to those involved.
Provide comfort where there is pain.
Bring clarity where there is confusion.
Let your will be done.

In Jesus' name, Amen.

[Generated by APM with compassion and care]
  `.trim();
}

/**
 * Generate encouragement
 */
async function generateEncouragement(task) {
  return `
Dear friend,

Regarding: ${task.description}

Remember that you are not alone in this journey. Every challenge you face 
is an opportunity for growth. The fact that you're seeking help shows 
wisdom and courage.

"Be strong and courageous. Do not be afraid; do not be discouraged, 
for the Lord your God will be with you wherever you go." - Joshua 1:9

You matter. Your struggles matter. And help is available.

With encouragement,
APM (AI Prompt Manager)
  `.trim();
}

/**
 * Find relevant scripture
 */
async function findScripture(task) {
  const keywords = (task.description || '').toLowerCase();
  
  const scriptures = {
    'fear': 'Isaiah 41:10 - "Fear not, for I am with you; be not dismayed, for I am your God."',
    'anxiety': 'Philippians 4:6-7 - "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God."',
    'hope': 'Romans 15:13 - "May the God of hope fill you with all joy and peace as you trust in him."',
    'strength': 'Isaiah 40:31 - "But those who hope in the Lord will renew their strength."',
    'love': 'John 3:16 - "For God so loved the world that he gave his one and only Son."',
    'peace': 'John 14:27 - "Peace I leave with you; my peace I give you."',
    'guidance': 'Proverbs 3:5-6 - "Trust in the Lord with all your heart and lean not on your own understanding."'
  };
  
  for (const [key, verse] of Object.entries(scriptures)) {
    if (keywords.includes(key)) {
      return `Relevant Scripture:\n\n${verse}\n\nMay this word bring comfort and guidance.`;
    }
  }
  
  return `Scripture for reflection:\n\nPsalm 23:1 - "The Lord is my shepherd, I lack nothing."\n\nWhatever you're facing, remember you are cared for.`;
}

/**
 * General empathy response
 */
async function generateEmpathyResponse(task) {
  return `
I hear you regarding: ${task.description}

Your feelings are valid. It's okay to struggle, and it's brave to reach out.

Here's what I want you to know:
1. You're not alone in this
2. This situation is temporary, even if it doesn't feel that way
3. Taking one small step forward is still progress
4. Asking for help is a sign of strength, not weakness

How can I support you further?

With empathy,
APM
  `.trim();
}

// ============================================
// EXPRESS API
// ============================================

const app = express();
app.use(express.json());

app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    agent: 'APM',
    specialties: apm.specialties,
    is_conductor: apm.isConductor
  });
});

app.get('/api/status', async (req, res) => {
  const repid = await apm.getRepID();
  res.json({
    agent: 'APM',
    repid_score: repid,
    is_conductor: apm.isConductor,
    specialties: apm.specialties,
    constitutional_mode: true
  });
});

app.post('/api/pray', async (req, res) => {
  const { intention } = req.body;
  const prayer = await generatePrayer({ description: intention });
  res.json({ prayer });
});

app.listen(PORT, () => {
  console.log(`[APM] API listening on port ${PORT}`);
});

// Start the agent
apm.run(processTask).catch(err => {
  console.error('[APM] Fatal error:', err);
  process.exit(1);
});
