#!/usr/bin/env bash
# sync-agents.sh — one source of truth for the shared subagent AND skill sets.
#
# The name still says "agents" because generated files across four repos cite it
# by path; renaming it would orphan those headers for no gain. It syncs both.
#
# Claude Code loads subagents from each project's own `.claude/agents/`, and
# these are five separate git repositories, so the set has to exist in each one.
# That is a duplication, and duplication drifts — the lesson `sprint-lib.js`
# records after a parser was copied byte-for-byte into its own test file.
#
# So the copies are GENERATED, never hand-edited, and each carries a header
# saying so. Edit the canonical file here, re-run this, commit the result.
#
# NOT BUILT: a CI check that fails when a copy has drifted from the canonical.
# Until that exists this is a convention, not a fence — stated plainly rather
# than implied, because a mechanism wired at one end is worse than an absent one.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANON="$ROOT/.claude/agents"
# Defaults resolve against the SIBLING directory of this repo, not the caller's
# cwd — running it from scripts/ silently found nothing the first time.
TARGETS=("$@")
[ ${#TARGETS[@]} -eq 0 ] && TARGETS=("$ROOT/../repid-engine" "$ROOT/../trinity-ecosystem" "$ROOT/../trustshell")
SKILLS="$ROOT/.claude/skills"

# Splice the GENERATED banner in after a file's YAML frontmatter, so the
# frontmatter Claude Code parses stays the first thing in the file. Used for
# both agents and SKILL.md, which share that shape.
emit_with_banner() {  # $1=src  $2=dest  $3=canonical-path-for-the-note
  local f="$1" out="$2" note="$3" fm
  # `|| true` is load-bearing under `set -euo pipefail`: grep exits 1 when a file
  # has no frontmatter (every references/*.md), and pipefail then killed the whole
  # sync after the first such file — silently, having written only the agents.
  fm="$(grep -n '^---$' "$f" | sed -n 2p | cut -d: -f1 || true)"
  if [ -n "$fm" ]; then
    { head -n "$fm" "$f"
      printf '\n<!-- GENERATED by trinity-symphony-shared/scripts/sync-agents.sh — do not edit here.\n     Canonical source: %s -->\n' "$note"
      tail -n +"$(( fm + 1 ))" "$f"
    } > "$out"
  else
    # No frontmatter (the references/*.md). A leading comment is safe there.
    { printf '<!-- GENERATED by trinity-symphony-shared/scripts/sync-agents.sh — do not edit here.\n     Canonical source: %s -->\n\n' "$note"
      cat "$f"
    } > "$out"
  fi
}

for t in "${TARGETS[@]}"; do
  [ -d "$t" ] || { echo "skip (absent): $t"; continue; }

  mkdir -p "$t/.claude/agents"
  for f in "$CANON"/*.md; do
    b="$(basename "$f")"
    emit_with_banner "$f" "$t/.claude/agents/$b" "trinity-symphony-shared/.claude/agents/$b"
    echo "  wrote $t/.claude/agents/$b"
  done

  # Skills are DIRECTORIES, and each repo also has skills of its own that this
  # script must never touch. So it copies only the directories that exist under
  # the canonical tree, and leaves every other entry in the target alone. A
  # blanket rsync --delete here would silently eat repo-local skills.
  [ -d "$SKILLS" ] || continue
  for d in "$SKILLS"/*/; do
    [ -d "$d" ] || continue
    n="$(basename "$d")"
    mkdir -p "$t/.claude/skills/$n"
    while IFS= read -r -d '' f; do
      rel="${f#"$d"}"
      mkdir -p "$t/.claude/skills/$n/$(dirname "$rel")"
      case "$rel" in
        *.md) emit_with_banner "$f" "$t/.claude/skills/$n/$rel" "trinity-symphony-shared/.claude/skills/$n/$rel" ;;
        *)    cp "$f" "$t/.claude/skills/$n/$rel" ;;
      esac
    done < <(find "$d" -type f -print0)
    echo "  wrote $t/.claude/skills/$n/ ($(find "$d" -type f | wc -l | tr -d ' ') files)"
  done
done
