#!/usr/bin/env bash
# sync-agents.sh — one source of truth for the shared subagent set.
#
# Claude Code loads subagents from each project's own `.claude/agents/`, and
# these are five separate git repositories, so the set has to exist in each one.
# That is a duplication, and duplication drifts — the lesson `sprint-lib.js`
# records after a parser was copied byte-for-byte into its own test file.
#
# So the copies are GENERATED, never hand-edited, and each carries a header
# saying so. Edit the canonical file here, re-run this, commit the result.
#
# NOT BUILT: a CI check that fails when a copy has drifted from the canonical.
# Until that exists this is a convention, not a fence — stated plainly rather
# than implied, because a mechanism wired at one end is worse than an absent one.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANON="$ROOT/.claude/agents"
# Defaults resolve against the SIBLING directory of this repo, not the caller's
# cwd — running it from scripts/ silently found nothing the first time.
TARGETS=("$@")
[ ${#TARGETS[@]} -eq 0 ] && TARGETS=("$ROOT/../repid-engine" "$ROOT/../trinity-ecosystem" "$ROOT/../trustshell")
for t in "${TARGETS[@]}"; do
  [ -d "$t" ] || { echo "skip (absent): $t"; continue; }
  mkdir -p "$t/.claude/agents"
  for f in "$CANON"/*.md; do
    b="$(basename "$f")"
    out="$t/.claude/agents/$b"
    { head -n "$(grep -n '^---$' "$f" | sed -n 2p | cut -d: -f1)" "$f"
      printf '\n<!-- GENERATED by trinity-symphony-shared/scripts/sync-agents.sh — do not edit here.\n     Canonical source: trinity-symphony-shared/.claude/agents/%s -->\n' "$b"
      tail -n +"$(( $(grep -n '^---$' "$f" | sed -n 2p | cut -d: -f1) + 1 ))" "$f"
    } > "$out"
    echo "  wrote $out"
  done
done
